name: Install Website to S3 Bucket

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET_NAME: friends-capstone-s3-website

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies in Package.json
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Check Build Folder
      run: cd build && ls -latr

    - name: Upload to S3 Website Bucket
      uses: shallwefootball/s3-upload-action@master
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}     
        aws_bucket: ${{ AWS_S3_BUCKET_NAME }}
        source_dir: build
