name: Install Website to S3 Bucket

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_CAPTCHA_KEY: ${{ secrets.AWS_CAPTHCA_KEY }}
  AWS_S3_BUCKET_NAME: friends-capstone-infra-s3-website

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies in Package.json
      run: npm install --force

    - name: Replace Variables
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#'
        tokenSuffix: '#'
        files: '["**/src/utilities/Constants.js"]'
      env:
        AWS_CAPTCHA_KEY: "${{ env.AWS_CAPTCHA_KEY }}"

    - name: Build
      run: npm run build

    - name: Check Build Folder
      run: cd build && ls -latr

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to S3
      run: aws s3 sync --delete ./build s3://${{env.AWS_S3_BUCKET_NAME}}
